global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "nodes"
    static_configs:
      - targets:
          - "node1:8000"
          - "node2:8000"
          - "node3:8000"
          - "node4:8000"
          - "node5:8000"
          - "node6:8000"
